apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: civic-pulse-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: civic-pulse-backend
  template:
    metadata:
      labels:
        app: civic-pulse-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_SERVER
              value: "{{ .Values.backend.env.postgresServer }}"
            - name: POSTGRES_USER
              value: "{{ .Values.backend.env.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.backend.env.postgresDatabase }}"
            - name: SECRET_KEY
              value: "{{ .Values.backend.env.secretKey }}"
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
