global:
  environment: production

backend:
  replicaCount: 3
  image:
    repository: ghcr.io/chiraghs/civic-pulse-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  env:
    postgresServer: "postgres-db-service"
    postgresUser: "postgres"
    postgresDatabase: "civic_pulse"
    secretKey: "k8s-prod-signing-jwt-secret-key"

frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/chiraghs/civic-pulse-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

postgres:
  enabled: true
  storageSize: 10Gi
  password: "k8s-production-postgres-password"

redis:
  enabled: true

ingress:
  enabled: true
  host: civicpulse.gov
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
